-- create database asn3;


CREATE TABLE SRC_RETAIL_STORE (
	RETAIL_CD VARCHAR(100) NOT NULL,
	RETAIL_NAME VARCHAR(100) NOT NULL,
	RETAIL_ADDRESS VARCHAR(100) NOT NULL,
	RETAIL_REGION VARCHAR(100) NOT NULL,
	CONSTRAINT SRC_RETAIL_STORE_PK PRIMARY KEY (RETAIL_CD)
);

CREATE TABLE SRC_PRODUCT_DATA (	
	PROD_CD VARCHAR(100) NOT NULL,
	PROD_DESC VARCHAR(100) NOT NULL,
	PROD_PRICE DECIMAL(18, 2) NOT NULL,
	CONSTRAINT SRC_PRODUCT_DATA_PK PRIMARY KEY (PROD_CD)
);

CREATE TABLE SRC_CUSTOMER_DATA (
	CUST_NAME VARCHAR(100) NOT NULL,
	CUST_MOB VARCHAR(100) NOT NULL,
	CUST_EMAIL VARCHAR(100) NOT NULL,
	CUST_ADDR VARCHAR(100) NOT NULL
);

CREATE TABLE SRC_EMP_DATA (
	EMP_CD VARCHAR(100) NOT NULL,
	RETAIL_CD VARCHAR(100) NOT NULL,
	EMP_NAME VARCHAR(100) NOT NULL,
	EMP_GENDER VARCHAR(1) NOT NULL,
	EMP_DOB DATE NOT NULL,
	EMP_ADDRESS VARCHAR(100) NOT NULL,
	CONSTRAINT SRC_EMP_DATA_PK PRIMARY KEY (EMP_CD)
);

CREATE TABLE SRC_SALES (
	ORDER_ID VARCHAR(100) NOT NULL,
	ORDER_DATE DATE NOT NULL,
	PROD_CD VARCHAR(100) NOT NULL,
	EMP_CD VARCHAR(100) NOT NULL,
	RETAIL_CD VARCHAR(100) NOT NULL,
	CUST_CD VARCHAR(100) NOT NULL,
	QUANTITY INT NOT NULL,
	AMOUNT_PAID DECIMAL(12, 2) NOT NULL
);

